# --- Build Stage ---
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and lock file first (better cache)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the app
RUN npm run build


# --- Production Stage ---
FROM nginx:alpine

# Set working directory for Nginx
WORKDIR /usr/share/nginx/html

# Copy the built output from the previous stage
COPY --from=builder /app/dist .

# Copy template and entrypoint
COPY nginx.conf.template /etc/nginx/conf.d/nginx.conf.template
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
