version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_PASSWORD: shani
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/todo
    depends_on:
      - mysql
    command: sh -c "npx prisma db push && node index.js"
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    environment:
      VITE_API_URL: "/api/todos"
      BACKEND_URL: "http://backend:3001/"
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mysql_data:
