apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shani768/todo-app-eks-k8s-gitops.git
    targetRevision: HEAD
    path: k8s-deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true           # Automatically delete resources removed from git
      selfHeal: true        # Automatically sync if drift detected
    syncOptions:
      - CreateNamespace=true  # Create the namespace if missing
