apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            - sh
            - -c
            - 'until nc -z mysql 3306; do echo "waiting for mysql"; sleep 3; done; echo "mysql is up"'
      containers:
        - name: backend    
          image: shani000786/kubernates-project-01-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: mysql://root:root@mysql.default.svc.cluster.local:3306/todo
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001
