apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shani000786/kubernates-project-01-frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VITE_API_URL
              value: "/api/todos"
            - name: BACKEND_URL
              value: "http://backend:3001/"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
